### ISSUE TITLE
Link to episode video

### ISSUE THREAD

**Issue by morevnaproject** [Yuemashi/mori_002#1]
Can you please add a link to the final video fo the episode in Readme file, so people can watch the result? ^__^

**Comment by Yuemashi** [comment]
@morevnaproject Thank you for your interest! 
We are preparing the final video. Perhaps we can add final videos in early June.

But there are some copyrights problems (Character voice and BGMs are licensed files). So we cannot make the master video to open accsess. We can add a no-music and no-voice video only. Someday, if rights problems are settled, we will upload original master.

**Comment by Yuemashi** [comment]
**We add the final video of this project at [The story of Mikasa station ep2](https://youtu.be/2KTJUhluFiU) !**
We hopes it will be helpful for other animation projects!

Thank you @morevnaproject !
